export const ADD_PROJECT = 'ADD_PROJECT';
export const UPDATE_PROJECT = 'UPDATE_PROJECT';
export const REMOVE_PROJECT = 'REMOVE_PROJECT';
export const PUBLISH_PROJECT = 'PUBLISH_PROJECT';
export const UNPUBLISH_PROJECT = 'UNPUBLISH_PROJECT';
export const GET_PROJECT = 'GET_PROJECT';
export const PROJECT_ERROR = 'PROJECT_ERROR';

export const ON_EDIT_PROJECT = 'ON_EDIT_PROJECT';
export const ON_REMOVE_PROJECT = 'ON_REMOVE_PROJECT';
export const ON_PUBLISH_PROJECT = 'ON_PUBLISH_PROJECT';
export const ON_UNPUBLISH_PROJECT = 'ON_UNPUBLISH_PROJECT';

export const CLEAR_CURRENT_SELECTION = 'CLEAR_CURRENT_SELECTION';
