// Related to the project
export const IS_ENABLED = 'IS_ENABLED';
export const ADD_PROJECT = 'ADD_PROJECT';
export const UPDATE_PROJECT = 'UPDATE_PROJECT';
export const REMOVE_PROJECT = 'REMOVE_PROJECT';
export const PUBLISH_PROJECT = 'PUBLISH_PROJECT';
export const UNPUBLISH_PROJECT = 'UNPUBLISH_PROJECT';
export const ON_EDIT_PROJECT = 'ON_EDIT_PROJECT';
export const ON_REMOVE_PROJECT = 'ON_REMOVE_PROJECT';
export const ON_PUBLISH_PROJECT = 'ON_PUBLISH_PROJECT';
export const ON_UNPUBLISH_PROJECT = 'ON_UNPUBLISH_PROJECT';

// Related to the offer
export const SUBMIT_OFFER = 'SUBMIT_OFFER';
export const CANCEL_OFFER = 'CANCEL_OFFER';
export const ACCEPT_PROPOSAL = 'ACCEPT_PROPOSAL';
export const REJECT_PROPOSAL = 'REJECT_PROPOSAL';
export const ON_SUBMIT_OFFER = 'ON_SUBMIT_OFFER';
export const ON_CANCEL_OFFER = 'ON_CANCEL_OFFER';
export const ON_ACCEPT_PROPOSAL = 'ON_ACCEPT_SERVICES';
export const ON_REJECT_PROPOSAL = 'ON_REJECT_PROPOSAL';

// Related to the contract
export const DELIVER_PROJECT = 'DELIVER_PROJECT';
export const CANCEL_SERVICES = 'CANCEL_SERVICES';
export const ACCEPT_DELIVERY = 'ACCEPT_DELIVERY';
export const REJECT_DELIVERY = 'REJECT_DELIVERY';
export const CANCEL_CONTRACT = 'CANCEL_CONTRACT';
export const ON_DELIVER_PROJECT = 'ON_DELIVER_PROJECT';
export const ON_CANCEL_SERVICES = 'ON_CANCEL_SERVICES';
export const ON_ACCEPT_DELIVERY = 'ON_ACCEPT_DELIVERY';
export const ON_REJECT_DELIVERY = 'ON_REJECT_DELIVERY';
export const ON_CANCEL_CONTRACT = 'ON_CANCEL_CONTRACT';

// Ratings
export const RATINGS_ISSUER = 'RATINGS_ISSUER';
export const RATINGS_FULFILLER = 'RATINGS_FULFILLER';
export const ON_RATINGS_FULFILLER = 'ON_RATINGS_FULFILLER';
export const ON_RATINGS_ISSUER = 'ON_RATINGS_ISSUER';

// Events
export const NEW_EVENT = 'NEW_EVENT';
export const SETUP_EVENT = 'SETUP_EVENT';
export const UNSUBSCRIBED_ALL_EVENTS = 'UNSUBSCRIBED_ALL_EVENTS';

// Misc
export const ON_CANCEL_MODAL = 'ON_CANCEL_MODAL';
export const CLEAR_CURRENT_SELECTION = 'CLEAR_CURRENT_SELECTION';

// Related to the getter
export const GET_PROJECT = 'GET_PROJECT';
export const GET_PROJECT_DETAIL = 'GET_PROJECT_DETAIL';

// Related to the errors
export const PROJECT_ERROR = 'PROJECT_ERROR';

// Related to firebase
export const CURRENT_USER = 'CURRENT_USER';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const RESET_SUCCESS = 'RESET_SUCCESS';
export const RESET_FAIL = 'RESET_FAIL';
export const LOGOUT = 'LOGOUT';

// Notifications
export const NOTIFICATION_EVENT = 'NOTIFICATION_EVENT';
export const NOTIFICATION_ERROR = 'NOTIFICATION_ERROR';
export const NOTIFICATION_CLEAR_ERRORS = 'NOTIFICATION_CLEAR_ERRORS';
export const NOTIFICATION_CLEAR_EVENTS = 'NOTIFICATION_CLEAR_EVENTS';
export const NOTIFICATION_CLEAR_ALL = 'NOTIFICATION_CLEAR_ALL';

// Alerts and errors
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
