// Related to the project
export const IS_ENABLED = 'IS_ENABLED';
export const ADD_PROJECT = 'ADD_PROJECT';
export const UPDATE_PROJECT = 'UPDATE_PROJECT';
export const REMOVE_PROJECT = 'REMOVE_PROJECT';
export const PUBLISH_PROJECT = 'PUBLISH_PROJECT';
export const UNPUBLISH_PROJECT = 'UNPUBLISH_PROJECT';
export const ON_EDIT_PROJECT = 'ON_EDIT_PROJECT';
export const ON_REMOVE_PROJECT = 'ON_REMOVE_PROJECT';
export const ON_PUBLISH_PROJECT = 'ON_PUBLISH_PROJECT';
export const ON_UNPUBLISH_PROJECT = 'ON_UNPUBLISH_PROJECT';

// Related to the offer
export const SUBMIT_OFFER = 'SUBMIT_OFFER';
export const CANCEL_OFFER = 'CANCEL_OFFER';
export const ACCEPT_PROPOSAL = 'ACCEPT_PROPOSAL';
export const REJECT_PROPOSAL = 'REJECT_PROPOSAL';
export const ON_SUBMIT_OFFER = 'ON_SUBMIT_OFFER';
export const ON_CANCEL_OFFER = 'ON_CANCEL_OFFER';
export const ON_ACCEPT_PROPOSAL = 'ON_ACCEPT_SERVICES';
export const ON_REJECT_PROPOSAL = 'ON_REJECT_PROPOSAL';

// Related to the contract
export const DELIVER_PROJECT = 'DELIVER_PROJECT';
export const CANCEL_SERVICES = 'CANCEL_SERVICES';
export const ACCEPT_DELIVERY = 'ACCEPT_DELIVERY';
export const REJECT_DELIVERY = 'REJECT_DELIVERY';
export const CANCEL_CONTRACT = 'CANCEL_CONTRACT';
export const ON_DELIVER_PROJECT = 'ON_DELIVER_PROJECT';
export const ON_CANCEL_SERVICES = 'ON_CANCEL_SERVICES';
export const ON_ACCEPT_DELIVERY = 'ON_ACCEPT_DELIVERY';
export const ON_REJECT_DELIVERY = 'ON_REJECT_DELIVERY';
export const ON_CANCEL_CONTRACT = 'ON_CANCEL_CONTRACT';

// Events
export const ON_SUBSCRIBE_EVENT = 'ON_SUBSCRIBE_EVENT';
export const SUBSCRIBED_EVENT = 'SUBSCRIBED_EVENT';
export const ON_UNSUBSCRIBE_EVENT = 'ON_UNSUBSCRIBE_EVENT';
export const UNSUBSCRIBED_EVENT = 'UNSUBSCRIBED_EVENT';
export const ON_UNSUBSCRIBE_ALL_EVENTS = 'ON_UNSUBSCRIBE_ALL_EVENTS';
export const UNSUBSCRIBED_ALL_EVENTS = 'UNSUBSCRIBED_ALL_EVENTS';
export const NEW_EVENT = 'NEW_EVENT';

// Misc
export const ON_CANCEL_MODAL = 'ON_CANCEL_MODAL';
export const CLEAR_CURRENT_SELECTION = 'CLEAR_CURRENT_SELECTION';

// Related to the getter
export const GET_PROJECT = 'GET_PROJECT';

// Related to the errors
export const PROJECT_ERROR = 'PROJECT_ERROR';
